//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Cube_prefab
    {
        public const string BundleName = "cube_prefab";
        public const string CUBE = "cube";
    }
    public class Map_prefab
    {
        public const string BundleName = "map_prefab";
        public const string MAP = "map";
    }
    public class V2_prefab
    {
        public const string BundleName = "v2_prefab";
        public const string V2 = "v2";
    }
}
